### ISSUE TITLE
Investigate i18n/l10n Packages for react-core

### ISSUE THREAD

**Issue by redallen** [patternfly/patternfly-react#2093]
Default strings could be localized using a package we endorse. Styling could also be conditional based on localization.

**Comment by Hyperkid123** [comment]
I don't think that any i18n package should be integrated. If you want to localize strings just let users to customize them. Sure you can give a recommendation in pf core as an example but what if the app is migrating from PF3 to PF4 and there is already i18n system in place? The only way is to allow string customization.

Imo any string constant in component that cannot be changed via props is actually a bug and should be fixed.

cc @martinpovolny @karelhala

**Comment by martinpovolny** [comment]
In ManageIQ UI we use gettext based i18n for everything.
In Sources/Topology on Insights we use React-intl.

These are just 2 solution from just 2 projects.

From the perspective of the diversity of different project and products that use PF, I would like PF to be i18n tool agnostic.

String customization in PF 3/4 is the way to the full i18n while not forcing PF users into using a particular approach.

In ManageIQ we are on PF3 and want to start adding PF4 in the next release. We have i18n infrastructure in place and do not plan or want to change it. From that perspective if PF4 was to come with integrated i18n it's one more problem to deal with. A problem that would make the migration to PF4 more expensive.

I can imagine that when starting a completely new application it's more convenient to have the i18n part of the library. In the context of starting a new app it's ok if the component library is opinionated in this way. This argument however holds only early in the development and only short-term.

I am confident that with the rate of changes in the Javascript landscape compared with the length of life of the various (Red Hat and community) projects and products the benefit is overcome by the downsides.

PF4 is to replace PF3 in many existing projects and products so, please, do not make that (already painful) task even more painful.

One cannot expect a project that lives over 10 years to switch to an different i18n solution because of a new version of an UI library.

Please, do not make our work hard.

CC: @h-kataria, @dmetzger57.

**Comment by dlabaj** [comment]
Agree that this should not be part of patternfly.

**Comment by ssilvert** [comment]
> I don't think that any i18n package should be integrated. If you want to localize strings just let users to customize them. Sure you can give a recommendation in pf core as an example but what if the app is migrating from PF3 to PF4 and there is already i18n system in place? The only way is to allow string customization.
> 
> Imo any string constant in component that cannot be changed via props is actually a bug and should be fixed.
> 
> cc @martinpovolny @karelhala

The above would be a nice simple solution (call it **option 1**).  However there is a downside.  It means that every project using PF4 is responsible for doing its own translations.  That's a lot of duplicated effort.

The other solution I can think of is to go ahead and implement something using an existing i18n/l10n library.  (**option 2**)

If a project doesn't want to use the same i18n/l10n library as PF4, that's OK.  The only downside there is that you have to load two libraries.

I suspect that the number of strings needing localization in PF4 is rather small.  Therefore, a lightweight custom solution should be considered (**option 3**).  

I rolled my own for Keycloak because all the packages I considered were too big and complicated for what we needed.  If later we need a lot of the bells and whistles offered by the other packages, we will just bite the bullet and make the switch.  It took more time to evaluate other libraries than it did to write one myself.

Lastly, I will say that doing nothing should not be an option.  PF4 must be localizable.

**Comment by ssilvert** [comment]
> Agree that this should not be part of Patternfly. This was discussed earlier on and was decided that it would be up to the consumer to choose how to support i18n.

@dlabaj Doing nothing doesn't solve the problem as long as there are hard-coded strings in PF4.  Are you saying that you want to go with option 1?

If so, it would be helpful if you at least provided files with key/value pairs for common locales.  That way, applications using PF4 could import translations into whatever library they are using.  And, the community could contribute new translations.  Otherwise, every project will have to duplicate that effort.

**Comment by martinpovolny** [comment]
>  The only way is to allow string customization.

I assume that is the solution. Is that correct, @dlabaj? 

> I suspect that the number of strings needing localization in PF4 is rather small. 

That is my assuption too.

**Comment by karelhala** [comment]
> > I don't think that any i18n package should be integrated. If you want to localize strings just let users to customize them. Sure you can give a recommendation in pf core as an example but what if the app is migrating from PF3 to PF4 and there is already i18n system in place? The only way is to allow string customization.
> > Imo any string constant in component that cannot be changed via props is actually a bug and should be fixed.
> > cc @martinpovolny @karelhala
> 
> The above would be a nice simple solution (call it **option 1**). However there is a downside. It means that every project using PF4 is responsible for doing its own translations. That's a lot of duplicated effort.

The best way here would be to allow all string to be changed, currently there are few of them that can't be changed and that is a showstopper for translations. Consumers can pass any string to any component it doesn't have to be translated strings it could be anything so looking at it from usability perspective not forcing consumers to use one translate library is a good thing.

> The other solution I can think of is to go ahead and implement something using an existing i18n/l10n library. (**option 2**)
> 
> If a project doesn't want to use the same i18n/l10n library as PF4, that's OK. The only downside there is that you have to load two libraries.
> 
> I suspect that the number of strings needing localization in PF4 is rather small. Therefore, a lightweight custom solution should be considered (**option 3**).

Yes you are correct multiple strings will eventually be translated by multiple teams so there will be same srings translated by multiple teams, however PF team should not focus on this because thereś a ton of other work they have to work on and translation shouldn't really be part of these components. On other hand we as community could come up with package that has all default string translated using selected library, however this package will not be maintained by PF team directly, it will just be reference somewhere as prefered way but not dicated.

> 
> I rolled my own for Keycloak because all the packages I considered were too big and complicated for what we needed. If later we need a lot of the bells and whistles offered by the other packages, we will just bite the bullet and make the switch. It took more time to evaluate other libraries than it did to write one myself.
> 
> Lastly, I will say that doing nothing should not be an option. PF4 must be localizable.

**Comment by ssilvert** [comment]
> The best way here would be to allow all string to be changed, currently there are few of them that can't be changed and that is a showstopper for translations.

If that's true then this issue definitely needs to be reopened.  You are correct.  That is absolutely a showstopper.  We can't have English text show up in an app translated to another locale.


> Yes you are correct multiple strings will eventually be translated by multiple teams so there will be same srings translated by multiple teams, however PF team should not focus on this because thereś a ton of other work they have to work on and translation shouldn't really be part of these components. On other hand we as community could come up with package that has all default string translated using selected library, however this package will not be maintained by PF team directly, it will just be reference somewhere as prefered way but not dicated.

I disagree here.  We are all working toward the same goal and "PF team doesn't have time" is not a good excuse to force other teams to duplicate effort.  These strings live in the PF code base and it is therefore PF's responsibility to provide some way to make them localizable.

I think that the community can help with translations, but it only makes sense that translation mapping files live somewhere in a PF repo where the PF team has ultimate responsibility.

**Comment by karelhala** [comment]
> > The best way here would be to allow all string to be changed, currently there are few of them that can't be changed and that is a showstopper for translations.
> 
> If that's true then this issue definitely needs to be reopened. You are correct. That is absolutely a showstopper. We can't have English text show up in an app translated to another locale.
> 
I think you missunderstood me before, let me try to explain it differently. I wouldn't say reopen the issue, because this one is focused on translation, however we should open a new issue to allow change of any string used in any component (as some kind of tracker issue). So anybody can use whichever library they want.

> > Yes you are correct multiple strings will eventually be translated by multiple teams so there will be same srings translated by multiple teams, however PF team should not focus on this because thereś a ton of other work they have to work on and translation shouldn't really be part of these components. On other hand we as community could come up with package that has all default string translated using selected library, however this package will not be maintained by PF team directly, it will just be reference somewhere as prefered way but not dicated.
> 
> I disagree here. We are all working toward the same goal and "PF team doesn't have time" is not a good excuse to force other teams to duplicate effort. These strings live in the PF code base and it is therefore PF's responsibility to provide some way to make them localizable.

That is exactly what I was refering before, PF team has to allow any string to be changed. However we can't use any translation library not because that would pull any library but because what if some app tries to translate to some language that would not be translated by initial PF team? And they'd use different library. They would have to use different format eventually for subset of strings and that is a no go.

> 
> I think that the community can help with translations, but it only makes sense that translation mapping files live somewhere in a PF repo where the PF team has ultimate responsibility.

It could be under PF org should they decide to support one library for instance, but it shouldn't be part of react core library. Because react core library is only about components not about translations.

**Comment by ssilvert** [comment]
> > I think that the community can help with translations, but it only makes sense that translation mapping files live somewhere in a PF repo where the PF team has ultimate responsibility.
> 
> It could be under PF org should they decide to support one library for instance, but it shouldn't be part of react core library. Because react core library is only about components not about translations.

Every localizable library is "about" translations.  If you want to claim that pf-react can be localized then you need to make it easy for developers to do localization.

Apparently, it has been decided that the i18n solution for pf-react is to allow changing all English text through attributes on components.  And that part is fine.

But the translations should live where the original text lives.  Again, we don't want everyone who uses pf-react to duplicate effort and re-invent its own translations.

All you have to do is create a directory under the react-core project and add translation files.  Pick any format you want.  https://www.transifex.com/blog/2016/common-localization-file-formats/

Then you just provide the file for English (and maybe one other language).  The community will send you PR's for other languages.  This is how we do it in Keycloak and we now support 15 languages.  Almost all of those were contributed by the community.
