### ISSUE TITLE
Login Page interaction issues

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-react#986]
There were two issues identified while doing an IxD review of the Login Page.

(1) The Language Selector should behave as a select list, i.e. selecting Spanish should change the label to Spanish. **This depends on issue #1214** 

(2) Input fields should not display an error state (red border) prior to validation. Default state should be displayed when this page is loaded and the user has not yet interacted with the page.  **This is fixed by core in PR** [*#1227*](https://github.com/patternfly/patternfly-next/pull/1227)

**Comment by tlabaj** [comment]
@mcarrano   number (1) can not be addressed until issue #718 is resolve.  Dropdown select is not implemented in React yet.
Can you please give more info in number (2).  I was unable to reproduce it..

**Comment by rachael-phillips** [comment]
We'll need the P1 label for this one for Beta

**Comment by tlabaj** [comment]
@rachael-phillips The second point is addressed by core.  I updated description above.  The First point is dependent on the custom select (single select) component.

**Comment by rachael-phillips** [comment]
@tlabaj thanks for the comment!

**Comment by LHinson** [comment]
the language selector on the login page PR was closed without being merged to wait for designs: https://github.com/patternfly/patternfly-next/pull/1610 Therefore I've removed the rc.1 tag

**Comment by mcarrano** [comment]
I think that the Language Selector issue is still pending, but not sure where it is on the roadmap. There is a core issue here: https://github.com/patternfly/patternfly-next/issues/349 @rachael-phillips can you help sort this out? I think this issue remains open unless it is now covered somewhere else.

**Comment by jenny-s51** [comment]
Hi @mcarrano, it looks like the language selector was removed from the login page in this release: https://github.com/patternfly/patternfly-react/compare/@patternfly/react-core@2.1.1...@patternfly/react-core@2.1.2

Can this issue be closed?

**Comment by mcarrano** [comment]
I think this issue can be closed @jenny-s51 . There is an open issue in core here to add the language selector in the background area of the page: https://github.com/patternfly/patternfly-next/issues/1821. It may make sense to close this and open a new React issue when the time is right as this issue was related to the old designs.

@rachael-phillips what do you think?

**Comment by jenny-s51** [comment]
closing per @rachael-phillips
